name: EndRestriction
version: '${version}'
main: net.lumalyte.endrestrict.EndRestrictionPlugin
api-version: '1.20'
description: Restricts access to The End until a configured time
author: lumalyte
softdepend: [PlaceholderAPI]

permissions :
  testplugin.readconfig:
    description: Read config.yml values - /read-config <ultimate-answer|pangram|boolean|player>
    default: true
  testplugin.flyspeed:
    description: Sets the fly speed of the player executing the command - /flyspeed <speed>
    default: true
  testplugin.flyspeed.others:
    description: Sets the fly speed of other players - /flyspeed <player> <speed>
    default: op

# No need to add "commands", as it would conflict with the new PaperMC command registration system.
